# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: edbc9d14dcc9173dcbd25a182d0632bd32399d956cf1d403dca3ffd35c51949772ba791dc2cdd6cd61931b42ef6b3609c204d8c434339606f2c40825e49dab4a

test:
  secret_key_base: 69f610a4dc402ffacf5a8e9da66c0287ab8f228a732501a307b1dddafd8ae525d52ac1ee12e36de7cfd9303cfd6be44ad8256903de2b41660f02b1a66b27c418

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
